socialnetwork/accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

socialnetwork/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('postDetail/<int:pk>', views.PostDetailView.as_view(), name='postDetail'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('createPost/', views.CreatePostView.as_view(), name='createPost'),
    path('like/<int:post_id>', views.LikePostView.as_view(), name='like'),
    path('comment/<int:post_id>', views.CommentView.as_view(), name='comment'),
]

socialnetwork/socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialnetwork/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SocialNetwork</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar">
        <ul>
            <img style="width: 28px;" href={% url 'home:home' %} src={{ navbarLogo.image.url }}>
            <li><a href={% url 'home:home' %}>Home</a></li>
            {% if request.user.is_authenticated %}
                <li><a href={% url 'accounts:logout' %}>Logout</a></li>
                <li><a href={% url 'home:profile' request.user.id%}>Profile</a></li>
            {% else %}
                <li><a href={% url 'accounts:register' %}>Register</a></li>
                <li><a href={% url 'accounts:login' %}>Login</a></li>
            {% endif %}
        </ul>
    </nav>
    
    <div class="bodySite" style="padding: 20px;">
        <center>
            <img style="width: 270px;" href={% url 'home:home' %} src={{ topLogo.image.url }}>
        </center>
        <!-- Message Box -->
        {% if messages %}
            <div class="message-box">
                {% for msg in messages %}
                    <h2>{{ msg }}</h2>
                {% endfor %}
            </div>
        {% endif %}
        <div style="padding: 30px">
            {% block content %}{% endblock %}
        </div>
        <center>
            {% if posts %}
                {% for post in posts %}
                    <div class="card" style="display: inline-block; width: 18rem; height: 18rem" >
                        <img src="{{ post.picture.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p>{{ post.date_posted }}</p>
                            <a class="btn btn-primary" href={% url "home:postDetail" post.id %}>Read More</a>
                        </div>
                    </div>
                 {% endfor %}
            {% endif %}
        </center>
    </div>

</body>
</html>