socialnetwork/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('postDetail/<int:pk>', views.PostDetailView.as_view(), name='postDetail'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('createPost/', views.CreatePostView.as_view(), name='createPost'),
    path('like/<int:post_id>', views.LikePostView.as_view(), name='like'),
    path('comment/<int:post_id>', views.CommentView.as_view(), name='comment'),
]

socialnetwork/socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialnetwork/home/models.py
from datetime import timezone

from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    author = models.CharField(max_length=100)
    picture = models.ImageField(upload_to="posts/%Y/%m/%d")
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class LikeRelation(models.Model):
    postLikedId = models.CharField(max_length=100)
    postLikedBy = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.postLikedId} liked by {self.postLikedBy}'



class CommentsModel(models.Model):
    commentAuthor = models.CharField(max_length=100)
    commentOnPost = models.CharField(max_length=100)
    comment = models.TextField()
    commentDate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.commentAuthor} commented on {self.commentOnPost}'



class PicOfTheSite(models.Model):
    image = models.ImageField(upload_to="pics/%Y/%m/%d")
    imageName = models.CharField(max_length=100)
    def __str__(self):
        return self.imageName

socialnetwork/home/forms.py
from tokenize import Comment

from django import forms

from home.models import Post, CommentsModel


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['picture', 'title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentsModel
        fields = ['comment']

        labels = {'comment': 'add your comment'}

socialnetwork/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from home.models import Post, LikeRelation, CommentsModel, PicOfTheSite
from django.contrib.auth.models import User
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class HomeView(View):
    def get(self, request):
        topLogo = PicOfTheSite.objects.get(imageName='top logo of the site')
        navbarLogo = PicOfTheSite.objects.get(imageName='navbar logo')
        posts = Post.objects.all()
        return render(request, 'home/home.html', {'posts': posts, 'topLogo': topLogo, 'navbarLogo': navbarLogo})

class PostDetailView(View):
    template_name = 'home/postDetail.html'
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        like = LikeRelation.objects.filter(postLikedId=pk).count()
        comments = CommentsModel.objects.filter(commentOnPost=pk)
        return render(request, self.template_name, {'post': post, 'like': like, 'comments': comments})


class ProfileView(View):
    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        userPosts = Post.objects.filter(author=user.username)
        return render(request, 'home/profileView.html', {'user': user, 'userPosts': userPosts})


class CreatePostView(LoginRequiredMixin, View):
    form_class = forms.PostCreateForm
    template_name = 'home/postCreate.html'
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            Post.objects.create(author=request.user.username, picture=cd['picture'], title=cd['title'], content=cd['content'])
            messages.success(request, 'Your post has been created!')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        is_exists = LikeRelation.objects.filter(postLikedId=post_id, postLikedBy=request.user.username)
        if is_exists is None:
            messages.error(request, 'You have already liked this post!')
            return redirect('home:postDetail', pk=post_id)
        else:
            LikeRelation.objects.create(postLikedId=post_id, postLikedBy=request.user.username)
            messages.success(request, 'You liked this post!')
            return redirect('home:postDetail', pk=post_id)


class CommentView(LoginRequiredMixin, View):
    form_class = forms.CommentForm
    template_name = 'home/comment.html'
    def get(self, request, post_id):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, post_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            CommentsModel.objects.create(commentAuthor=request.user.username, commentOnPost=post_id, comment=cd['comment'])
            messages.success(request, 'Your comment has been posted!')
            return redirect('home:postDetail', pk=post_id)
        else:
            messages.error(request, 's.th went wrong!')
            return redirect('home:postDetail', pk=post_id)

socialnetwork/home/templates/home/comment.html
{% extends 'base.html' %}

{% block content %}
    <center>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input value="create" type="submit" class="btn btn-primary">
        </form>
    </center>
{% endblock %}

socialnetwork/home/templates/home/home.html
{% extends 'base.html' %}


{% block content %}

{% endblock %}

socialnetwork/home/templates/home/postCreate.html
{% extends 'base.html' %}

{% block content %}
    <center>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input value="create" type="submit" class="btn btn-primary">
        </form>
    </center>
{% endblock %}

socialnetwork/home/templates/home/postDetail.html
{% extends 'base.html' %}

{% block content %}
    <center>
        <h2>{{ post.author }} : </h2><h1>{{ post.title }}</h1><br/>
        <img src="{{ post.picture.url }}"><br/><br/>
        <h3>{{ post.content }}</h3>
        <p>{{ post.date_posted }}</p>
        <a class="btn btn-danger" href={% url 'home:like' post.pk %}>LIKE {{ like }}</a>
        <a class="btn btn-warning" href={% url 'home:comment' post.pk %}>Comment</a><br/><br/>

        {% if comments %}
            {% for comment in comments %}
                <center>
                    <h2>_______________________________________________________________________________________________</h2>
                    <h2 class="text-break">{{ comment.commentAuthor }} : </h2><h3>{{ comment.comment }} . ({{ comment.commentDate }})</h3>
                </center>
            {% endfor %}
        {% endif %}

    </center>
{% endblock %}

socialnetwork/home/templates/home/profileView.html
{% extends 'base.html' %}


{% block content %}
    <center>
        <h1>Profile Page</h1><br/>
        <h2>{{ user.username }}</h2><br/>
        {% if request.user.username == user.username %}
            <a class="btn btn-primary" href={% url 'home:createPost' %}>Create New Post</a><br/><br/>
        {% endif %}
        {% if userPosts %}
            {% for post in userPosts %}
                <div class="card" style="display: inline-block; width: 18rem; height: 18rem;" >
                    <img src="{{ post.picture.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p>{{ post.date_posted }}</p>
                        <a href={% url "home:postDetail" post.id %}>Read More</a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </center>
{% endblock %}